name: Build LLVM Toolchain (Windows)

on:
    workflow_dispatch:

jobs:
    windowsBuild:
        name: Windows Build
        runs-on: windows-2022
        env:
            BUILD_PROJECT: llvm
            BUILD_MASTER: false
            LLVM_VERSION: 17.0.6

        strategy:
            fail-fast: false
            matrix:
                CRT:
                -   libcmt

                TARGET_CPU:
                -   x86

                CONFIGURATION:
                -   Release

        steps:
        -   name: Checkout repo
            uses: actions/checkout@v3

        -   name: Installing LLVM Toolchain
            shell: cmd
            run: |
                call %GITHUB_WORKSPACE%\windows\set-env.bat msvc17 ${{matrix.CRT}} ${{matrix.TARGET_CPU}} ${{matrix.CONFIGURATION}}
                call %GITHUB_WORKSPACE%\windows\install.bat

        -   name: Build LLVM Toolchain
            id: BUILD
            shell: cmd
            run: |
                call %GITHUB_WORKSPACE%\windows\set-env.bat msvc17 ${{matrix.CRT}} ${{matrix.TARGET_CPU}} ${{matrix.CONFIGURATION}}
                call %GITHUB_WORKSPACE%\windows\build.bat
                echo ::set-output name=DEPLOY_FILE::%DEPLOY_FILE%

        -   name: Release
            uses: softprops/action-gh-release@v1
            if: startsWith(github.ref, 'refs/tags/')
            env:
                GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
            with:
                files: ${{steps.BUILD.outputs.DEPLOY_FILE}}
