name: Build LLVM Toolchain (Windows)

on:
  push:
    tags:
      - 'LLVM-WINDOWS-v*.*.*'

jobs:
    windowsBuild:
        name: Build LLVM Toolchain (Windows)
        runs-on: windows-2022
        env:
            BUILD_PROJECT: llvm
            BUILD_MASTER: false
            LLVM_VERSION: 17.0.6

        strategy:
            fail-fast: false
            matrix:
                CRT:
                -   libcmt

                TARGET_CPU:
                -  amd64

                CONFIGURATION:
                -   MinSizeReel

        steps:
        -   name: Checkout repo
            uses: actions/checkout@v3

        -   name: Generating Unique ID
            shell: cmd
            run: call %GITHUB_WORKSPACE%\windows\generate-build-id.bat

        -   name: Installing LLVM Toolchain
            shell: cmd
            run: |
                call %GITHUB_WORKSPACE%\windows\set-env.bat msvc17 ${{matrix.CRT}} ${{matrix.TARGET_CPU}} ${{matrix.CONFIGURATION}}
                call %GITHUB_WORKSPACE%\windows\install.bat

        -   name: Build LLVM Toolchain
            id: BUILD
            shell: cmd
            run: |
                call %GITHUB_WORKSPACE%\windows\set-env.bat msvc17 ${{matrix.CRT}} ${{matrix.TARGET_CPU}} ${{matrix.CONFIGURATION}}
                call %GITHUB_WORKSPACE%\windows\build.bat
                echo ::set-output name=DEPLOY_FILE::%DEPLOY_FILE%

        -  name: Releasing LLVM Toolchain
           uses: softprops/action-gh-release@v2
           with:
              tag_name: ${{ env.BUILD_ID }}
              name: "LLVM Toolchain (Windows)"
              body: |
                ## LLVM Toolchain (Windows)
               
                LLVM - Clang (v17.0.6) binaries compiled with maximum optimizations for Windows x86_64 environments.
                
              files: ${{steps.BUILD.outputs.DEPLOY_FILE}}
              draft: false
