name: Build LLVM-C API (Linux)

on:
  push:
    tags:
      - 'LLVM-C-API-LINUX-v*.*.*'

jobs:
  build-llvm:
    runs-on: ubuntu-latest

    permissions:
      contents: write
  
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
  
    steps:
      - name: Generating Unique ID
        run: |
          BASE_NAME=$(echo "$GITHUB_REF" | sed 's|^refs/tags/||')
          BUILD_ID="${BASE_NAME}-$GITHUB_RUN_ID" 
          
          echo "BUILD_ID=$BUILD_ID" >> $GITHUB_ENV
          echo "BUILD_ID=$TAG_NAME" >> $GITHUB_ENV

          echo "Unique ID: $BUILD_ID"
          echo "Base name: $TAG_NAME"
    
      - name: Downloading LLVM project
        run: |
          wget https://github.com/llvm/llvm-project/releases/download/llvmorg-17.0.6/llvm-project-17.0.6.src.tar.xz

      - name: Unpacking LLVM project 
        run: |
          tar -xf llvm-project-17.0.6.src.tar.xz
          mv llvm-project-17.0.6.src llvm-project

      - name: Installing dependencies
        run: |
          sudo apt-get install -y build-essential cmake ninja-build python3 libz-dev binutils xz-utils 
          sudo apt-get remove -y llvm-16* clang-16*
          sudo rm -rf /usr/lib/llvm-16

      - name: Preparing for build (LLVM-C API)
        run: |
          mkdir build
          mkdir dist
          cd build
        working-directory: llvm-project/llvm
          
      - name: Configuring CMake (LLVM-C API)
        run: |
          cmake ../CMakeLists.txt -G Ninja -DLLVM_ENABLE_RUNTIMES="" -DLLVM_ENABLE_PROJECTS="llvm" -DCMAKE_INSTALL_PREFIX="../dist" -DCMAKE_BUILD_TYPE=MinSizeRel -DLLVM_TARGETS_TO_BUILD="X86" -DLLVM_BUILD_TESTS=OFF -DLLVM_BUILD_EXAMPLES=OFF -DLLVM_INCLUDE_TESTS=OFF -DLLVM_INCLUDE_EXAMPLES=OFF -DLLVM_INCLUDE_DOCS=OFF
        working-directory: llvm-project/llvm/build

      - name: Building LLVM-C API
        run: |
          ninja -j$(nproc) libLLVMAggressiveInstCombine.a libLLVMAnalysis.a libLLVMAsmParser.a libLLVMAsmPrinter.a libLLVMBinaryFormat.a libLLVMBitReader.a libLLVMBitWriter.a libLLVMBitstreamReader.a libLLVMCFGuard.a libLLVMCFIVerify.a libLLVMCodeGen.a libLLVMCodeGenTypes.a libLLVMCore.a libLLVMCoroutines.a libLLVMCoverage.a libLLVMDWARFLinker.a libLLVMDWARFLinkerParallel.a libLLVMDWP.a libLLVMDebugInfoBTF.a libLLVMDebugInfoCodeView.a libLLVMDebugInfoDWARF.a libLLVMDebugInfoGSYM.a libLLVMDebugInfoLogicalView.a libLLVMDebugInfoMSF.a libLLVMDebugInfoPDB.a libLLVMDebuginfod.a libLLVMDemangle.a libLLVMDiff.a libLLVMDlltoolDriver.a libLLVMExecutionEngine.a libLLVMExegesis.a libLLVMExegesisX86.a libLLVMExtensions.a libLLVMFileCheck.a libLLVMFrontendHLSL.a libLLVMFrontendOpenACC.a libLLVMFrontendOpenMP.a libLLVMFuzzMutate.a libLLVMFuzzerCLI.a libLLVMGlobalISel.a libLLVMIRPrinter.a libLLVMIRReader.a libLLVMInstCombine.a libLLVMInstrumentation.a libLLVMInterfaceStub.a libLLVMInterpreter.a libLLVMJITLink.a libLLVMLTO.a libLLVMLibDriver.a libLLVMLineEditor.a libLLVMLinker.a libLLVMMC.a libLLVMMCA.a libLLVMMCDisassembler.a libLLVMMCJIT.a libLLVMMCParser.a libLLVMMIRParser.a libLLVMObjCARCOpts.a libLLVMObjCopy.a libLLVMObject.a libLLVMObjectYAML.a libLLVMOption.a libLLVMOrcJIT.a libLLVMOrcShared.a libLLVMOrcTargetProcess.a libLLVMPasses.a libLLVMProfileData.a libLLVMRemarks.a libLLVMRuntimeDyld.a libLLVMScalarOpts.a libLLVMSelectionDAG.a libLLVMSupport.a libLLVMSymbolize.a libLLVMTableGen.a libLLVMTableGenCommon.a libLLVMTableGenGlobalISel.a libLLVMTarget.a libLLVMTargetParser.a libLLVMTextAPI.a libLLVMTransformUtils.a libLLVMVectorize.a libLLVMWindowsDriver.a libLLVMWindowsManifest.a libLLVMX86AsmParser.a libLLVMX86CodeGen.a libLLVMX86Desc.a libLLVMX86Disassembler.a libLLVMX86Info.a libLLVMX86TargetMCA.a libLLVMXRay.a libLLVMipo.a libLTO.so
          ninja -j$(nproc) llvm-config
        working-directory: llvm-project/llvm/build

      - name: Installing LLVM-C API
        run: |
          ninja install
        working-directory: llvm-project/llvm/build

      - name: Packaging LLVM-C API (Libraries)
        run: |
          tar --format=pax -cJf libs.tar.xz --exclude='*/*.o' --exclude='*/*.cmake' --exclude='*/*.d' lib
        working-directory: llvm-project/llvm/build

      - name: Packaging LLVM-C API (Includes)
        run: |
          tar --format=pax -cJf includes.tar.xz --exclude='*/*.o' --exclude='*/*.cmake' --exclude='*/*.d' include
        working-directory: llvm-project/llvm/dist

      - name: Releasing LLVM-C API
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.BUILD_ID }}
          name: ${{ env.BUILD_ID }}
          body: |
            ## LLVM-C API
           
            LLVM-C API (v17.0.6) libraries for Linux x86_64 environments.
            
          files: |
            llvm-project/llvm/build/bin/llvm-config
            llvm-project/llvm/build/libs.tar.xz
            llvm-project/llvm/includes.tar.xz
            
          draft: false
