name: GNU C Standard Library & GNU C Runtime.

on:
  push:
    tags:
      - 'GNU-LIBC-CRT-LINUX-v*.*.*'

jobs:
  build-glibc:
    runs-on: ubuntu-latest

    permissions:
      contents: write
  
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
  
    steps:
      - name: Generating Unique ID
        run: |
          BASE_NAME=$(echo "$GITHUB_REF" | sed 's|^refs/tags/||')
          BUILD_ID="${BASE_NAME}-$GITHUB_RUN_ID" 
          
          echo "BUILD_ID=$BUILD_ID" >> $GITHUB_ENV
          echo "BUILD_ID=$TAG_NAME" >> $GITHUB_ENV

          echo "Unique ID: $BUILD_ID"
          echo "Base name: $TAG_NAME"
    
      - name: Downloading Linux glibc
        run: |
          wget https://github.com/bminor/glibc/archive/refs/tags/glibc-2.41.tar.gz

      - name: Unpacking Linux glibc
        run: |
          tar -xf glibc-2.41.tar.gz 
          mv glibc-2.41 glibc

      - name: Installing dependencies
        run: |
          sudo apt-get install -y apt-transport-https build-essential ninja-build cmake coreutils curl git libzstd-dev software-properties-common clang lld gcc-13 libstdc++-13-dev
          
      - name: Preparing for build glibc
        run: |
          mkdir build
          mkdir dist
          cd build
        working-directory: glibc/
          
      - name: Configuring Linux glibc
        run: |
          ../configure --prefix="../dist" --enable-static-nss --disable-shared --enable-static-pie --with-static-libgcc 
        working-directory: glibc/build

      - name: Building Linux glibc
        run: |
          make -j$(nproc)
          make install 
        working-directory: glibc/build

      - name: Packaging Linux glibc
        run: |
          tar --format=pax -cJf glibc.tar.xz --exclude='*/*.cmake' --exclude='*/*.d' lib
        working-directory: glibc/dist
        
      - name: Releasing Linux x86_64 glibc
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.BUILD_ID }}
          name: "Linux x86_64 glibc"
          body: |
            ## Linux x86_64 glibc
           
            GNU C Standard Library & GNU C runtime.
            
          files: |
            glibc/dist/glibc.tar.xz
            
          draft: false
