name: GNU C Standard Library & GNU C Runtime.

on:
  push:
    tags:
      - 'GNU-LIBC-CRT-LINUX-v*.*.*'

jobs:
  build-glibc:
    runs-on: ubuntu-latest

    permissions:
      contents: write
  
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
  
    steps:
      - name: Generating Unique ID
        run: |
          BASE_NAME=$(echo "$GITHUB_REF" | sed 's|^refs/tags/||')
          BUILD_ID="${BASE_NAME}-$GITHUB_RUN_ID" 
          
          echo "BUILD_ID=$BUILD_ID" >> $GITHUB_ENV
          echo "BUILD_ID=$TAG_NAME" >> $GITHUB_ENV

          echo "Unique ID: $BUILD_ID"
          echo "Base name: $TAG_NAME"
    
      - name: Downloading Linux glibc
        run: |
          wget https://mirrors.kernel.org/gnu/glibc/glibc-2.39.tar.xz

      - name: Unpacking Linux glibc
        run: |
          tar -xf glibc-2.39.tar.xz
          mv glibc-2.39 glibc

      - name: Installing dependencies
        run: |
          sudo apt-get install -y apt-transport-https build-essential bison flex texinfo gawk python3 ninja-build cmake coreutils curl git libzstd-dev software-properties-common clang lld gcc-13 libstdc++-13-dev
          
      - name: Preparing for build glibc
        run: |
          mkdir build
          cd build
          sudo mkdir /opt/glibc-dist
        working-directory: glibc/
          
      - name: Configuring Linux glibc
        run: |
          ../configure --prefix="/opt/glibc-dist" --disable-werror CFLAGS="-O2 -D_FORTIFY_SOURCE=2" --with-static-libgcc --disable-multilib
        working-directory: glibc/build

      - name: Building Linux glibc
        run: |
          make -j8
          make install 
        working-directory: glibc/build

      - name: Packaging Linux glibc
        run: |
          sudo tar --format=pax -cJf glibc.tar.xz --exclude='*/*.cmake' --exclude='*/*.d' lib
        working-directory: /opt/glibc-dist
        
      - name: Releasing Linux x86_64 glibc
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.BUILD_ID }}
          name: "Linux x86_64 glibc"
          body: |
            ## Linux x86_64 glibc
           
            GNU C Standard Library & GNU C runtime.
            
          files: |
            /opt/glibc-dist/glibc.tar.xz
            
          draft: false
