name: MLIR-C API (Linux)

on:
  push:
    tags:
      - 'MLIR-C-API-LINUX-v*.*.*'

jobs:
  build-llvm:
    runs-on: ubuntu-latest

    permissions:
      contents: write
  
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
  
    steps:
      - name: Generating Unique ID
        run: |
          BASE_NAME=$(echo "$GITHUB_REF" | sed 's|^refs/tags/||')
          BUILD_ID="${BASE_NAME}-$GITHUB_RUN_ID" 
          
          echo "BUILD_ID=$BUILD_ID" >> $GITHUB_ENV
          echo "BUILD_ID=$TAG_NAME" >> $GITHUB_ENV

          echo "Unique ID: $BUILD_ID"
          echo "Base name: $TAG_NAME"
    
      - name: Downloading LLVM project
        run: |
          wget https://github.com/llvm/llvm-project/releases/download/llvmorg-17.0.6/llvm-project-17.0.6.src.tar.xz

      - name: Unpacking LLVM project 
        run: |
          tar -xf llvm-project-17.0.6.src.tar.xz
          mv llvm-project-17.0.6.src llvm-project

      - name: Installing dependencies
        run: |
          sudo apt-get install -y build-essential cmake ninja-build python3 libz-dev binutils xz-utils clang llvm lld

      - name: Preparing for build (MLIR-C API)
        run: |
          mkdir build
          mkdir dist
          cd build
          
        working-directory: llvm-project/llvm

      - name: Configuring CMake (MLIR C API)
        run: |
          cmake ../CMakeLists.txt \
          -G Ninja \
          -DCMAKE_C_COMPILER="clang" \
          -DCMAKE_CXX_COMPILER="clang++" \
          -DLLVM_USE_LINKER=lld \
          -DLLVM_ENABLE_PROJECTS="mlir" \
          -DCMAKE_INSTALL_PREFIX="../dist" \
          -DCMAKE_BUILD_TYPE=Release \
          -DLLVM_TARGETS_TO_BUILD="Native" 
        
        working-directory: llvm-project/llvm/build

      - name: Building MLIR C API
        run: |
          ninja -j$(nproc)
        working-directory: llvm-project/llvm/build

      - name: Installing MLIR C API
        run: |
          ninja install
        working-directory: llvm-project/llvm/build

      - name: Cloning MLIR C API
        shell: bash
        run: |
          mkdir -p tempDir/{lib,bin,include}
          
          cp -r llvm-project/llvm/dist/lib/* tempDir/lib/
          cp -r llvm-project/llvm/dist/bin/* tempDir/bin/
          cp -r llvm-project/llvm/dist/include/* tempDir/include/

      - name: Packaging MLIR C API (MLIR C API Libraries, Binaries & Includes)
        run: |
          tar --format=pax -cJf mlir-c-api-x64-linux.tar.xz --exclude='*/*.cmake' --exclude='*/*.o' --exclude='*/*.d' lib bin include
          
        working-directory: tempDir

      - name: Releasing MLIR C API
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.BUILD_ID }}
          name: "MLIR C API (Linux)"
          body: |
            ## MLIR C API
           
            MLIR C API (v17.0.6) libraries for Linux x64 environments.
            
          files: |
            tempDir/mlir-c-api-x64-linux.tar.xz
            
          draft: false
